### ISSUE TITLE
Heads up: Some popular services rely on let's encrypt order finalize location header outside RFC 8555 

### ISSUE THREAD

**Issue by DominikGebhart** [knrdl/acme-ca-server#139]
Just as a heads up: I ran into an issue using gitlab's let's encrypt integration aginst this implementation and it [turns out](https://community.letsencrypt.org/t/breaking-changes-in-asynchronous-order-finalization-api/195882), some popular services rely on order finalization to return the order-location in the location header.

Since RFC 8555 does not require this, they are basically relying on an implementation detail (Hyrum's Law comes to mind), but it might be worth to consider adding behind some feature flag.

Also, thank you for this project, it was extremely helpful for a very specific usecase

Regards

**Comment by knrdl** [comment]
Thanks for the feedback. I've added the header. Please try again with the edge image `knrdl/acme-ca-server:edge`

**Comment by DominikGebhart** [comment]
Perfect, thank you
